"""Added Roadmaps

Revision ID: 049978537dbb
Revises: ae323655e24b
Create Date: 2025-02-20 21:09:35.787462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049978537dbb'
down_revision = 'ae323655e24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmaps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('course_title', sa.String(length=50), nullable=False),
    sa.Column('course_resourses', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roadmap_courses')
    op.drop_table('roadmaps')
    # ### end Alembic commands ###
