"""Added cascade on delete to Academic notes

Revision ID: 543dbd5fdea7
Revises: a2ebb6225a45
Create Date: 2025-03-31 23:01:40.239149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543dbd5fdea7'
down_revision = 'a2ebb6225a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_notes', schema=None) as batch_op:
        batch_op.drop_constraint('academic_notes_note_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'notes', ['note_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('academic_notes_note_id_fkey', 'notes', ['note_id'], ['id'])

    # ### end Alembic commands ###
