"""Removed unnecessary columns

Revision ID: 7238c3bb9dab
Revises: 09e640753b01
Create Date: 2025-04-01 01:45:32.778129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7238c3bb9dab'
down_revision = '09e640753b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('desc')

    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_column('stack')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stack', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
