"""Queries

Revision ID: 76a5839372cc
Revises: dd231a3e3477
Create Date: 2025-03-08 20:04:14.717990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a5839372cc'
down_revision = 'dd231a3e3477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_title', sa.String(length=255), nullable=False),
    sa.Column('query_desc', sa.String(length=255), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('submitted_on', sa.DateTime(), nullable=False),
    sa.Column('stack', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('response', sa.String(length=255), nullable=False),
    sa.Column('responded_by', sa.Integer(), nullable=False),
    sa.Column('responded_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.ForeignKeyConstraint(['responded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queries_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('liked_by', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['liked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queries_likes')
    op.drop_table('responses')
    op.drop_table('queries')
    # ### end Alembic commands ###
