"""Removed Student table

Revision ID: 8d00974e2f73
Revises: 543dbd5fdea7
Create Date: 2025-03-31 23:22:07.415010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d00974e2f73'
down_revision = '543dbd5fdea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batch', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('passout_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stack', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('registration_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='student_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='student_pkey')
    )
    # ### end Alembic commands ###
