"""Removed Unnecessary tables

Revision ID: ad21b8c6b4fe
Revises: 8d00974e2f73
Create Date: 2025-04-01 01:25:16.994941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad21b8c6b4fe'
down_revision = '8d00974e2f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queries_likes')
    op.drop_table('alumni')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('passout_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('occupation', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('registration_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='alumni_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='alumni_pkey')
    )
    op.create_table('queries_likes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('liked_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('response_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['liked_by'], ['users.id'], name='queries_likes_liked_by_fkey'),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], name='queries_likes_query_id_fkey'),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], name='queries_likes_response_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='queries_likes_pkey')
    )
    # ### end Alembic commands ###
