"""Added Events Table

Revision ID: ae323655e24b
Revises: d1e2b9504259
Create Date: 2025-02-20 01:45:05.581677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae323655e24b'
down_revision = 'd1e2b9504259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('submitted_on', sa.DateTime(), nullable=False),
    sa.Column('poster_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
