"""Added notes

Revision ID: d1e2b9504259
Revises: 76cb42b17096
Create Date: 2025-02-19 21:01:40.957609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e2b9504259'
down_revision = '76cb42b17096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_notes', schema=None) as batch_op:
        batch_op.drop_column('year')

    # ### end Alembic commands ###
