"""Updated Roadmap Courses course_title length

Revision ID: dd231a3e3477
Revises: 049978537dbb
Create Date: 2025-02-20 22:14:34.064220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd231a3e3477'
down_revision = '049978537dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmap_courses', schema=None) as batch_op:
        batch_op.alter_column('course_title',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmap_courses', schema=None) as batch_op:
        batch_op.alter_column('course_title',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
