"""Added new col in Events

Revision ID: ef577b77fdb0
Revises: 1a8948364f92
Create Date: 2025-03-30 22:20:10.337366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef577b77fdb0'
down_revision = '1a8948364f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('know_more', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('know_more')

    # ### end Alembic commands ###
