"""Added Course LIst

Revision ID: fe6daba70997
Revises: 4cf8be0b85ac
Create Date: 2025-03-24 09:35:39.598918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6daba70997'
down_revision = '4cf8be0b85ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('course_code', sa.String(length=50), nullable=False),
    sa.Column('course_title', sa.String(length=150), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_list')
    # ### end Alembic commands ###
